import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {

	if (typeof window !== "undefined") {
		const theme = localStorage.getItem("theme");

		if (theme) {
			document.documentElement.classList.add("dark");
		} else {
			document.documentElement.classList.remove("dark");
		}
	}

	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
